version: '3.8'

services:
  stable-diffusion-webui:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3001"
      - "8888:8888"
    environment:
      JUPYTER_PASSWORD: "Jup1t3R!"
      ENABLE_TENSORBOARD: "1"
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
      HF_HUB_ENABLE_HF_TRANSFER: "1"
    restart: unless-stopped